#!/bin/bash

set -e

echo "Building a development Docker image"
docker build -t whats-the-score-dev .

[[ $# -eq 0 ]] && cmd="bash" || cmd="$@"
echo "Running ${cmd} in the development container"
docker run --rm -it \
    -v /app/node_modules \
    -v "$(pwd)":/app \
    -p 2112:2112 \
    whats-the-score-dev \
    $cmd
